### ISSUE TITLE
<master-name> is getting set incorrectly for sentinel directives in sentinel.conf

### ISSUE THREAD

**Issue by ostap36** [brianbianco/redisio#108]
Hello, first of all thank you for the cookbook.

Unless I am missing something (and I very well might be), I am seeing the "master-name" value in sentinel.conf.erb gets set from the following hash:
```
node['redisio']['sentinels'] 
```
So I'm ending up with master-name that has sentinel_ prefix such as this:

sentinel monitor sentinel_sentinel .....

As I understand this should rather be the logical name of the redis master. So shouldn't it be coming from ```node['redisio']['servers']``` hash for the array element that represents the master?

This is the erb snippet for sentinel's config.

```
# sentinel monitor <master-name> <ip> <redis-port> <quorum>
#
# Tells Sentinel to monitor this slave, and to consider it in O_DOWN
# (Objectively Down) state only if at least <quorum> sentinels agree.
#
# Note: master name should not include special characters or spaces.
# The valid charset is A-z 0-9 and the three characters ".-_".
# sentinel monitor mymaster 127.0.0.1 6379 2
sentinel monitor <%=@name%> <%=@masterip%> <%=@masterport%> 2
```

Is there a potential merge problem in the sentnel provider for cases where both ```node['redisio']['servers']``` and ```node['redisio']['sentinels']``` are overwritten in a wrapper cookbook

```
    #Retrieve the default settings hash and the current server setups settings hash.
    current_instance_hash = current_instance.to_hash
    current_defaults_hash = new_resource.sentinel_defaults.to_hash

    #Merge the configuration defaults with the provided array of configurations provided
    current = current_defaults_hash.merge(current_instance_hash)
```

**Comment by martinb3** [comment]
Hi there! I think this has been resolved with some of the referenced issues/commits. Please let us know if it's still a problem -- as we've refactored the existing hash to contain a master name field separately for each sentinel.
