### ISSUE TITLE
Test cookbook with redis 3.0 and investigate what changes will be needed to support it

### ISSUE THREAD

**Issue by brianbianco** [brianbianco/redisio#159]

**Comment by zarry** [comment]
3.0 is officially out there.  https://groups.google.com/forum/#!msg/redis-db/dO0bFyD_THQ/Uoo2GjIx6qgJ

**Comment by brianbianco** [comment]
I saw that, We should test this, I'm sure our users will too.  It would be nice to beat them to the punch.

**Comment by TinaTina** [comment]
:+1:

**Comment by mhenrixon** [comment]
:+1:

**Comment by mhenrixon** [comment]
Is anyone working on this?

**Comment by martinb3** [comment]
I'm not actively, but I did converge the cookbook on Friday against 2.6, 2.8, and 3.0, and they did all converge okay. Didn't get a chance to dig into it. I think we should settle #199 at the same time as this item.

**Comment by spuder** [comment]
I created a role that installs redis 3.0 on ubuntu 14.04

```
{
  "name": "redis-master",
  "description": "Manages redis cluster",
  "json_class": "Chef::Role",
  "default_attributes": {
    "redisio": {
      "version": "3.0.3",
      "safe_install": false,
      "default_settings": {
        "clusterenabled" : "yes"
      }
    }
  },
  "override_attributes": {

  },
  "chef_type": "role",
  "run_list": [
    "recipe[redisio]",
    "recipe[redisio::enable]"
  ],
  "env_run_lists": {

  }
}
```
```
root@lab-rds01:~# redis-server --version
Redis server v=3.0.3 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=3336cd07e3a94659
```
Initial smoke tests appear to work ok for me. Service starts, able to add data, and do basic redis-y stuff.

**Comment by shortdudey123** [comment]
Closing since cookbook converges fine w/ 3.x
