### ISSUE TITLE
Sentinel name is used as master name in sentinel configuration file template

### ISSUE THREAD

**Issue by martinb3** [brianbianco/redisio#161]
I find the master-name being set to the sentinel's name to be a bit counter-intuitive (https://github.com/brianbianco/redisio/blob/master/templates/default/sentinel.conf.erb#L18-L26):
```
# sentinel monitor <master-name> <ip> <redis-port> <quorum>
#
# Tells Sentinel to monitor this slave, and to consider it in O_DOWN
# (Objectively Down) state only if at least <quorum> sentinels agree.
#
# Note: master name should not include special characters or spaces.
# The valid charset is A-z 0-9 and the three characters ".-_".
# sentinel monitor mymaster 127.0.0.1 6379 2
sentinel monitor <%=@name%> <%=@masterip%> <%=@masterport%> <%= @quorum_count %>
```

It leads to cases where you login to the sentinel and run `SENTINEL masters` and you get a list back of masters that are the same name as your sentinel (instead of the instance names of the masters).

**Comment by redterror** [comment]
Dupe of https://github.com/brianbianco/redisio/issues/108 no?

**Comment by martinb3** [comment]
I suppose it's a dupe of #108.
