### ISSUE TITLE
could not find recipe uninstall for cookbook redisio

### ISSUE THREAD

**Issue by seperman** [brianbianco/redisio#169]
In the readme file it mentions about the uninstall recipe but it does not exist.

**Comment by brianbianco** [comment]
Whoops.  This was removed ages ago as it was almost never used and was experiencing bit rot.  This should be removed from the documentation.

**Comment by zarry** [comment]
Readme has been updated. Thanks for the callout @seperman

**Comment by seperman** [comment]
You are welcome.
