### ISSUE TITLE
package manager installs

### ISSUE THREAD

**Issue by timwelch** [brianbianco/redisio#177]
Hi! I would love to use this cookbook in my production environment, but we aren't allowed to install build tools there. We also use Yum (CentOS), and there is a REDIS package in the EPEL repository. Is there any way that you could move the install prereq recipe inside of the bypass_setup code block so that it doesn't run? I feel like the bypass_setup should also bypass the prereqs as well. :-)  Either that, or add another flag for "external_package_manager" ...

Like this...

unless node['redisio']['bypass_setup']
  include_recipe "redisio::_install_prereqs"
  include_recipe "redisio::install"
  include_recipe "redisio::configure"
end

...OR this...

unless node['redisio']['external_package_manager']
   include_recipe "redisio::_install_prereqs"
end

**Comment by brianbianco** [comment]
This seems reasonable to me.  It looks like those package installs should be shifted into the prereq recipe and then that should be put inside the bypass_setup block.  Why would you need the dev tools installed if you don't plan on installing the package?

I'll try to get this out soon for you.

**Comment by timwelch** [comment]
Fantastic! Thanks so much!

**Comment by zarry** [comment]
@timwelch This hopefully should address your concerns?  I just merged it this morning. 

https://github.com/brianbianco/redisio/pull/180

**Comment by svanzoest** [comment]
:+1: but Ubuntu 14.04 LTS

**Comment by zarry** [comment]
Is this issue good to close?  Are there any open questions/concerns?

**Comment by martinb3** [comment]
I think it's good to close. We support both flavors now.
