### ISSUE TITLE
Fedora tests in test-kitchen are currently failing

### ISSUE THREAD

**Issue by zarry** [brianbianco/redisio#181]
Just getting this down in here so I can circle back to correct it later. 

```
       Redis
         enables the redis service
         starts the redis service (FAILED - 1)
         is listening on port 6379

       Failures:

         1) Redis starts the redis service
            Failure/Error: expect(service 'redis6379').to be_running
              expected Service "redis6379" to be running
              /bin/sh -c systemctl\ is-active\ redis6379
              inactive

            # /tmp/busser/suites/serverspec/redisio_spec.rb:12:in `block (2 levels) in <top (required)>'

       Finished in 0.06692 seconds (files took 0.31559 seconds to load)
       3 examples, 1 failure

       Failed examples:

       rspec /tmp/busser/suites/serverspec/redisio_spec.rb:9 # Redis starts the redis service
```

**Comment by martinb3** [comment]
This appears to be a mismatch between serverspec and chef 12. Chef 12 has been changed to allow each service to customize which init system it uses (before, it was hard-coded per platform). Serverspec still assumes it should interrogate systemd for the status of the redis server, but systemd says it isn't running, while the sys-v style init script says it _is_ running.

**Comment by martinb3** [comment]
We need to adjust the test to check for sysv-style init scripts, or make redis compatible with systemd on Fedora 20.

**Comment by martinb3** [comment]
This PR fixes it, but it's not my favorite solution. I wish serverspec was better about checking sysv.

**Comment by zarry** [comment]
Commented on the PR. Looks good to me, maybe just bump the centos version in that PR as well to fix this https://github.com/brianbianco/redisio/issues/182
