### ISSUE TITLE
Did we just release? Did we want to wait on a few of the other things marked 2.3.0?

### ISSUE THREAD

**Issue by zarry** [brianbianco/redisio#191]
I think most of the stuff was ready...

cc/ @martinb3 @brianbianco

**Comment by martinb3** [comment]
I did do a release, based on #179.
> Feel free to cut a release.

It looks like you marked stuff 2.3.0 in the middle of while I was doing it.

**Comment by zarry** [comment]
Ahh ok, just an off timing thing.  Well we will update the milestone to 2.4.0 for the stuff that didn't make it :) no bigs.

Thanks for clarification!

**Comment by martinb3** [comment]
D'oh, okay... sorry about that!

**Comment by brianbianco** [comment]
I don't think this is a big deal. In reality we should probably release less stuff more often. Our schedules often disagree
