### ISSUE TITLE
Systemd support?

### ISSUE THREAD

**Issue by zapman449** [brianbianco/redisio#203]
I'm fighting with the init process.  It seems like I'd need to override the job_control variable and offer 'systemd' as an option, but I'm not seeing clearly how to do this.  I'm also not seeing how this variable gets

I could hack it and use 'daemonize yes' in redis, and 'Type=forking' in a seperately controlled file, but that feels yucky.

**Comment by martinb3** [comment]
systemd support is in the cookbook, but there's still an issue with `is-enabled` RE: #205.

**Comment by chewi** [comment]
systemd handling seems to be missing in the LWRP. It's only present in the configure recipe. The README mentions a service LWRP but that's long gone.

**Comment by shortdudey123** [comment]
Systemd support was added almost 2 yrs ago in https://github.com/brianbianco/redisio/commit/71469215cb3e1c7aedc78c8b3ab73a66881528a5

Problems with systemd are tracked in other issues
Please open a new issue if you find a problem w/ systemd configuration
