### ISSUE TITLE
Redis-cli not installed

### ISSUE THREAD

**Issue by rbhalla** [brianbianco/redisio#210]
I have a fresh vagrant box running Ubuntu 14.04. I've used the most basic cookbook setup:

```
include_recipe 'redisio'
include_recipe 'redisio::enable'
```

But am unable to confirm it is working because redis-cli doesn't seem to be installed. I also had to restart the machine before I saw the redis process so it's possible something failed although nothing was reported.

Reprovisioning does nothing.

I noted that the readme states this has only been tested with ubuntu 12.04, is that a factor here?

**Comment by martinb3** [comment]
Can you let us know if it's just not on your path? We typically install from source, so you'd find it in `/usr/local/bin/redis-cli`. I'm guessing it's there, but just not on your path.

**Comment by rbhalla** [comment]
Embarrassingly this was entirely my fault. When googling for this repo one of the top links is https://supermarket.chef.io/cookbooks/redisio/versions/1.0.0 which I clicked without much thought to the actual url. Turns out I was just installing the wrong version!
