### ISSUE TITLE
Can chef-brigade help in any way?

### ISSUE THREAD

**Issue by josephholsten** [brianbianco/redisio#214]
`redisio` is the most popular redis cookbook, and I'd like to help it thrive. Is there anything @chef-brigade can do to help out?

FYI: mrflip's `redis` cookbook is up for adoption, I'd very much like to merge it with `redisio` so this project can be the top search result in a supermarket search for "redis".

**Comment by brianbianco** [comment]
In reality this cookbook needs a 3.0 version rewrite.  I have a ton of ideas of great ways to do that but no time to implement them. I am open to whatever help the chef-brigade wants to bring to the table.

**Comment by zarry** [comment]
:+1: I suppor this being involved with both this cookbook and @chef-brigade

**Comment by martinb3** [comment]
> I have a ton of ideas of great ways to do that but no time to implement them.

:+1: I'm in the same boat. I think redis 3.0 support would be a good start.

**Comment by martinb3** [comment]
Or just figuring out what versions we do support, in https://github.com/brianbianco/redisio/issues/199.

**Comment by josephholsten** [comment]
ok, sounds like @chef-brigade is going to be a friend-of-redisio, but won't be annexing the sovereign state of `brianbianco/redisio`.

@brianbianco, I've added you as an owner to @chef-brigade so you can contribute to any of its repos. 

If you need any administrative help, want a slack channel, website, testing infra &c, just let us know. It doesn't need to have the brigade name anywhere on it.

**Comment by martinb3** [comment]
@josephholsten I'd love to be able to be added ot that Chef Brigade team as well, if that's possible. Cheers.

**Comment by zarry** [comment]
:+1: for @martinb3

**Comment by josephholsten** [comment]
@martinb3 DUN Dun dun...

**Comment by martinb3** [comment]
> @martinb3 DUN Dun dun...

@josephholsten hmmm?

**Comment by josephholsten** [comment]
@martinb3 sorry, I meant "Done." And I could have sworn that I did invite you. But I sent another one.

**Comment by zarry** [comment]
also you can join us on slack @martinb3. https://chefbrigade.io/
