### ISSUE TITLE
`node['redisio']['default_setting']['cluster-*]` never been used

### ISSUE THREAD

**Issue by chrisduong** [brianbianco/redisio#216]
in "attributes/default.rb", we define:

```
  'cluster-enabled'            => 'no',
  'cluster-config-file'        => nil, # Defaults to redis instance name inside of template if cluster is enabled.
```

But in "providers/configure.rb", we look for:

```
        :clusterenabled             => current['clusterenabled'],
          :clusterconfigfile          => current['clusterconfigfile'],
          :clusternodetimeout         => current['clusternodetimeout'],
```

**Comment by martinb3** [comment]
Looks like these were added in https://github.com/brianbianco/redisio/commit/0d4553be4221025f794e96951ace53baefa64f74 by @brianbianco. We should add a test for rendering this template as well, probably.

**Comment by shortdudey123** [comment]
Solved by https://github.com/brianbianco/redisio/pull/208
