### ISSUE TITLE
Why not manage config file with breadcrumb? 

### ISSUE THREAD

**Issue by spuder** [brianbianco/redisio#231]
There is a dance that you must do when using sentinel

> If deploying sentinel it is recommended that you set the node[:redisio][:sentinel][:manage_config] to false allowing chef to write out the initial config and then allow redis-sentiniel to manage.

This is hard and confusing. 

What if you used a breadcrumb to update that config file once?

``` ruby
template 'foo.config' do
  action :create
  not_if do File.exists?(foo.breadcrumb) end
end

file 'foo.breadcrumb' do
  content "If breadcrumb exists, foo.config wont be overwritten"
  action :create_if_missing
  notifies :restart,  "service['redis']" #This only restarts redis if the file was created
end
```

The first time chef runs, it will update the sentinel config, leave a breadcrumb, and restart redis. 
The second time, and every time after that that chef runs, the config will be ignored (as long as the breadcrumb file is not removed). 

I've covered this design pattern more on my blog: http://spuder.github.io/chef/design-pattern/chef-taste-tester-pattern/

I"d like to discuss any reason that might prevent this from being implemented.

**Comment by shortdudey123** [comment]
Closed via https://github.com/brianbianco/redisio/pull/232
