### ISSUE TITLE
the scheme redis does not accept registry part: sentinel_mycluster (or bad hostname?) (URI::InvalidURIError

### ISSUE THREAD

**Issue by opsline-ankur** [brianbianco/redisio#244]
Hello, 

We are using redisio cookbook to set up redis-sentinel cluster. We tried to use redis gem to get redis master via sentinel 

redis = Redis.new(url: 'redis://' + cluster_name, sentinels: sentinels, role: :master)

but we saw " the scheme redis does not accept registry part: sentinel_mycluster (or bad hostname?) (URI::InvalidURIError " error.  We are giving mycluster as the cluster name but seems like sentinel_ is getting prefixed from the provider. We manually tried to change the cluster name from sentinel_mycluster to sentinel-mycluster in the sentinel conf file and it worked fine. 

Is it possible to either make this change from sentinel_ to sentinel- in the provider OR better provide an option to override the cluster name ? 

Thanks

**Comment by shortdudey123** [comment]
This can be done with the `name` option under the sentinel config
