### ISSUE TITLE
How to set maxmemory dynamically?

### ISSUE THREAD

**Issue by scaryguy** [brianbianco/redisio#249]
Hi,

I'd like to formulate my `maxmemory` setting like this:
```ruby
node['memory']['total'][0..-3].to_i * 1024) * node['redis']['memory_usage_ratio'] / 100).to_i
```

By this way, I'd like to allocate. for example, 80% of the server RAM resources for Redis with a custom `node['redis']['memory_usage_ratio']` attribute.

I couldn't figure out how to override maxmemory config using the formula above.

**Comment by scalp42** [comment]
@scaryguy you should just add an attribute for usage in percent for it in your wrapper which then override the maxmemory setting.

**Comment by devsibwarra** [comment]
It looks like the `redisio_configure` provider supports this

https://github.com/brianbianco/redisio/blob/master/providers/configure.rb#L81-L87

Looks like you'd be able to set either the `node['redis']['default_settings']['maxmemory']` or the per-instance `servers` hash setting to `80%` for your example
