### ISSUE TITLE
slowlog-max-len is not set dynamically

### ISSUE THREAD

**Issue by RedWhiteMiko** [brianbianco/redisio#251]
In attributes, slowlog-max-len value exist, but not used in the templates.
https://github.com/brianbianco/redisio/blob/39d11e35a22f8b7214e961a3daacdbac7962f81f/attributes/default.rb#L115
https://github.com/brianbianco/redisio/blob/470ecc2193bd88a379a13b81641536baea515d1d/templates/default/redis.conf.erb#L449

**Comment by shortdudey123** [comment]
Solved by https://github.com/brianbianco/redisio/pull/253
