### ISSUE TITLE
Spelling and grammar mistakes in redis.conf template

### ISSUE THREAD

**Issue by katbyte** [brianbianco/redisio#257]
I am trying to duplicate a production redis.conf wth this cookbook and during a diff of the original and the cookbooks output i noticed there were quite a few mistakes (and additional comments). I have fixed the minor spelling and grammar issues and will create a PR.

**Comment by brianbianco** [comment]
Thanks! Look forward to it.

**Comment by martinb3** [comment]
Thanks @katbyte!
