### ISSUE TITLE
Update to 2.4.0

### ISSUE THREAD

**Issue by MirrorZ** [brianbianco/redisio#259]
The cookbook version 2.4.0 works fine for me but since the tag has not been updated, pulling from supermarket/github is impossible. Updating the tag to 2.4.0 would be great.

**Comment by predominant** [comment]
:+1:

**Comment by brianbianco** [comment]
Ok. I'll try to update the change log and get a release out to supermarket

**Comment by nellshamrell** [comment]
Please do!  I'm one of the engineers working on Supermarket at Chef, please let me know if there is anything I can do to help :)

**Comment by brianbianco** [comment]
@nellshamrell Unfortunately It's mostly just caused by my lack of bandwidth.  I don't have as much free time as I used to, and my job no longer uses Redis.  This severely cuts into my available time to dedicate to the project.  I usually just sit and pray that some friendly contributor fills in the gaps :)

**Comment by brianbianco** [comment]
@martinb3 @zarry I went through and updated the Changelog to the best of my ability for a 2.4.1 release.  Could either of you give it a quick look over and then let me know if you think there is any reason I shouldn't cut a 2.4.1 release and push it to supermarket?

**Comment by martinb3** [comment]
I think the changelog looks good... running the tests now :)

**Comment by brianbianco** [comment]
@martinb3 Let me know if you see any issues.  Got a signed tag ready to push out.

**Comment by martinb3** [comment]
I'm good for a release; the only one that I had trouble testing was the debian image, and it appears to be a mirror issue. :+1:

**Comment by brianbianco** [comment]
@martinb3 I had the same issue.  Everything else seemed fine.

**Comment by brianbianco** [comment]
2.4.2 has been released on the supermarket, and it has a release listed in github.

**Comment by MirrorZ** [comment]
Thanks a lot.
