### ISSUE TITLE
can't override default settings by setting them in servers attribute

### ISSUE THREAD

**Issue by borgified** [brianbianco/redisio#262]
> Default settings is a hash of default settings to be applied to to ALL instances. These can be overridden for each individual server in the servers attribute. If you are going to set logfile to a specific file, make sure to set syslog-enabled to no.
> 
> redisio['default_settings'] - { 'redis-option' => 'option setting' }

i couldn't override attributes like syslogenabled,maxmemory,maxmemorypolicy,maxmemorysamples. all these work under default_settings though. however, i need to specify different values  according to the server being configured.

im setting them in a role definition like this (knife role edit):

```
{
  "name": "redis-cache",
  "description": "Redis Cache server Role",
  "json_class": "Chef::Role",
  "default_attributes": {
    "redisio": {
      "version": "3.0.7",
      "job_control": "systemd",
      "default_settings": {

      },
      "servers": [
        {
          "port": "6379",
          "syslogenabled": "no",
          "maxmemory": "1000000000",
          "maxmemorypolicy": "volatile-ttl",
          "maxmemorysamples": "10"
        },
        {
          "port": "6380",
          "syslogenabled": "no",
          "maxmemory": "13000000000",
          "maxmemorypolicy": "volatile-lru",
          "maxmemorysamples": "10"
        }
      ]
    }
  },
  "override_attributes": {
  },
  "chef_type": "role",
  "run_list": [
    "recipe[redisio::default]",
    "recipe[redisio::enable]"
  ],
  "env_run_lists": {

  }
}
```

**Comment by dwashko** [comment]
I had a similar issue, but it was hit or miss. I was able to override clusterenable in servers but I was not able to override logfile and syslogenabled. I had to specifically set my overrides for those in using:

default['redisio']['default']['logfile'] = '/var/log/redis/redis.log'

in a role cookbook.

**Comment by sogos** [comment]
I think the configuration file is protected in re-write by design. If the
config file is already here, the file is not regenerated after a change in
configuration.

**Comment by dwashko** [comment]
Yes that file is protected by breadcrumb, but if you delete the breadcrumb it will overwrite. That is not my problem. Like the original poster of the problem indicated, on the initial run, I am not able to override some of the settings using the servers hash. I noted the two specific ones that were not working for me:

loglevel
syslogenabled

I was not able to override those in the servers hash.

**Comment by sogos** [comment]
Can you test

In file : providers/configure.rb

After:

current = current_defaults_hash.merge(current_instance_hash)

Add:

p current

And  make a run to see the content  of  hash merge ?

**Comment by dwashko** [comment]
Hmmm I just did this from the raw cookbook setting server overrides in the .kitchen.yml file and ti worked fine. I am going to have to try this in my role cookbook and see what the deal is. I will get back to you on this.

**Comment by dwashko** [comment]
I am going to rescind my comment and say I am no longer having this problem. I am not sure why it was not working for me before but now the server hash is overriding the values as expected.

**Comment by martinb3** [comment]
If you're no longer encountering this issue, I'll go ahead and close 👍
