### ISSUE TITLE
Client recipe?

### ISSUE THREAD

**Issue by JCotton1123** [brianbianco/redisio#263]
I am already using your cookbook to setup Redis. I was looking over the recipes and resources and trying to find an appropriate way to install the redis-cli command without doing too much else. It seems like maybe copying default.rb to client.rb and removing `include_recipe "redisio::configure"` might be sufficient. Thoughts?

**Comment by martinb3** [comment]
I've used `node['redisio']['bypass_setup']` to bypass setup, and then I just include `redisio::default` and I get all the software installed. Is it possible you're also missing a /usr/local/bin/ from your path, and you might already have redis-cli? Hope this helps!

**Comment by brianbianco** [comment]
Closing this ticket.  Would be willing to accept a PR for a client recipe but Martin's answer seems workable until that happens.
