### ISSUE TITLE
Service Definition Has User Hardcoded

### ISSUE THREAD

**Issue by rossedman** [brianbianco/redisio#265]
If you change the user and group of the Redis service it is still [hardcoded in the systemctl definition](https://github.com/brianbianco/redisio/blob/master/templates/default/redis%40.service.erb#L8). Has anyone else experienced problems with this?

```
[Unit]
Description=Redis persistent key-value database
After=network.target

[Service]
ExecStart=<%= @bin_path %>/redis-server /etc/redis/%i.conf --daemonize no
ExecStop=/usr/bin/redis-shutdown
User=redis
Group=redis

[Install]
WantedBy=multi-user.target
```

**Comment by martinb3** [comment]
It sounds like we should add a test for this. If you've already got a fix handy, I'd be glad to review/merge it.

**Comment by shortdudey123** [comment]
Solved by https://github.com/brianbianco/redisio/pull/302
