### ISSUE TITLE
Missing /usr/bin/redis-shutdown script

### ISSUE THREAD

**Issue by maoueh** [brianbianco/redisio#271]
Hi,

I'm installing redis using cookbok version 2.4.2 on CentOS 7 using a wrapper cookbook (mainly to enforce version installed and default server settings).

I noticed the `systemd` script has its `ExecStop` command set to `/usr/bin/redis-shutdown`. However. when installing, this command does not exist. Is this file supposed to be present when installing by default?

This does not create apparent problem has `systemd` is smart enough to kill the process. However, for guaranteed persistence, the `redis` daemon must be  gracefully stopped. Also, even if the start command is templated with `%i`, the shutdown command seems not so I wonder what it was supposed to do.

ping @benLogN

**Comment by maoueh** [comment]
Here the current "fixup" recipe I'm currently using in my wrapper script. However, even if it's working, I think a single generic unit file for `systemd` is not correct because `user` and `group` can be different by server. As such, I did not find a way yet to make it generic based on the server name. To fully support all uses cases, I guess one unit for each service would be a better option.

Also, I did found some problems on CentOS with the current unit. The redis `run_dir` is in a `tmpfs` filesystem. On reboot, the folder is cleared up. On the next reboot, the `/var/run/redis` folder is not re-created by the unit preventing the service from starting. My fixup recipe fix this also.

```
# _finalize_systemd.rb
template "#{node['redisio']['bin_path']}/redis-shutdown" do
  source 'redis-shutdown.erb'
  user 'redis'
  group 'redis'
  mode '0755'
  variables(
    bin_dir: node['redisio']['bin_path'],
    redis_servers: node['redisio']['servers']
  )
end

template "/usr/lib/systemd/system/redis@.service" do
  source 'systemd/redis@.service.erb'
  user 'root'
  group 'root'
  mode '0644'
  variables(
    user: node['redisio']['default_settings']['user'],
    group: node['redisio']['default_settings']['group'],
    bin_dir: node['redisio']['bin_path'],
    run_dir: node['redisio']['base_piddir']
  )

  notifies :run, 'bash[reload systemd units]', :immediately

  node['redisio']['servers'].each do |redis_server|
    notifies :restart, "service[redis@#{redis_server['name']}]", :delayed
  end
end

bash 'reload systemd units' do
  code 'systemctl daemon-reload'

  action :nothing
end
```

```
# templates/default/redis-shutdown.erb
#!/usr/bin/env sh

##
# Generated by Chef
#
# Script that shut down a named redis instance
#

case $1 in
<% @redis_servers.each do |redis_server| %>
"<%= redis_server['name'] %>")
  exec <%= @bin_dir %>/redis-cli -h 127.0.0.1 -p <%= redis_server['port'] %> shutdown
  ;;
<% end %>
*)
  echo "No instance named '${1}' is known to this script."
  exit 1
  ;;
esac

echo "Should never reached here, something gone wrong!"
exit 2
```

```
# templates/default/systemd/redis@.service.erb
[Unit]
Description=Redis (%i) persistent key-value database
After=network.target

[Service]
PermissionsStartOnly=true
ExecStartPre=/bin/mkdir -p <%= @run_dir %>/%i
ExecStartPre=/bin/chown <%= @user %>:<%= @group %> <%= @run_dir %>/%i
ExecStart=<%= @bin_dir %>/redis-server /etc/redis/%i.conf --daemonize no
ExecStop=<%= @bin_dir %>/redis-shutdown %i
ExecStopPost=/bin/rm -rf <%= @run_dir %>/%i
User=<%= @user %>
Group=<%= @group %>

[Install]
WantedBy=multi-user.target
```

**Comment by chewi** [comment]
The redis-shutdown part is dealt with in #302. I haven't looked at the `/var/run/redis` issue yet but this should be fixed with `tmpfiles.d` instead.
