### ISSUE TITLE
Ubuntu 16.04: systemd path issues

### ISSUE THREAD

**Issue by Botje** [brianbianco/redisio#283]
Trying to use this cookbook with Ubuntu 16.04, I found two issues:
1. With `job_control` set to `systemd`, the cookbook attempts to create `/usr/lib/systemd/system/redis@.service`, but on Ubuntu 16.04 `/usr/lib/systemd/system` does not exist.
2. After installing the service file, `/usr/bin/systemctl daemon-reload` is called. On Ubuntu, this command should be `/bin/systemctl daemon-reload`.

**Comment by brianbianco** [comment]
Thanks!  I will try to patch this ASAP.

**Comment by chewi** [comment]
This is fixed in #302.

**Comment by yakatz** [comment]
This also fixes the issue for me. Any chance of it making it into a release?

**Comment by brianbianco** [comment]
Yes sorry. I've been busy. Will try to prioritize some pull requests and cut a release next week.

**Comment by shortdudey123** [comment]
Solved by https://github.com/brianbianco/redisio/pull/302
