### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by caramcc** [brianbianco/redisio#290]
In #285 you mentioned you were working on cutting a new release and that you hoped to have it by the end of July. Is there any update on this? I'd like to use the latest version of Redis (3.2.3) but can't easily without the changes introduced in #289.

Happy to help with this however I can!

**Comment by brianbianco** [comment]
Sorry.  I have been so far behind in other things I haven't been able to give this any attention.  The main things that need to happen before a release are:

1. Update changelog to reflect all actual changes in the release
2. Bump the version number appropriately in the metadata file (ideally this should have been done in ADVANCE)
3. Run all tests to make sure things aren't completely broken

Once those things are done I can cut a release and push it to the supermarket as well as create a tag in github.

**Comment by caramcc** [comment]
I opened #291 which has the changelog/version number updates. Also ran all tests - one tiny bugfix, but past that nothing failed.

**Comment by brianbianco** [comment]
Thanks for the PR handling this.  I know it's not a glamorous job but I've very thankful you did it.  Who knows how long this release would have taken without your contribution.
