### ISSUE TITLE
Recipe fails in case you run it on Amazon linux 2016.03

### ISSUE THREAD

**Issue by swapnil-jaiswal** [brianbianco/redisio#292]
Amazon Linux is identified as rhel family but the latest version (Amazon Linux 2016.03) still based on Init hence we will require following update

if node['platform_family'] == 'rhel' && Gem::Version.new(node['platform_version']  ) > Gem::Version.new('7.0.0') &&  node['platform'] != 'amazon'

instead of original 
if node['platform_family'] == 'rhel' && Gem::Version.new(node['platform_version']) > Gem::Version.new('7.0.0')

updated file : redisio\attributes/default.rb  uploaded with .txt extension 

[default.rb.txt](https://github.com/brianbianco/redisio/files/476707/default.rb.txt)

**Comment by petewilcock** [comment]
+1 for this, I'm hitting this issue and I'm stuck on 2.3.0 where I'm hitting other bugs trying to deploy redis to Amazon Linux.

**Comment by shortdudey123** [comment]
Closing since amazon is no longer detected as RHEL and is its own family 
https://github.com/chef/ohai/commit/a6bc18d974623dace652044df7796a4c52ff5107
