### ISSUE TITLE
Support for scripts in Sentinel template

### ISSUE THREAD

**Issue by quulah** [brianbianco/redisio#304]
Hi,

I'd like to have a way of defining the executable scripts for Sentinel. Currently the [template](https://github.com/brianbianco/redisio/blob/master/templates/default/sentinel.conf.erb#L116) is missing a way of pushing in `client-reconfig-script` and `notification-script`.

I currently have a workaround for this, but getting the scripts in the same way as the rest of the parameters from attributes would be welcome.

**Comment by shortdudey123** [comment]
Solved via https://github.com/brianbianco/redisio/pull/342 and released on 2.6.0
