### ISSUE TITLE
How can I specify the 'protected_mode' attribute for Sentinel?

### ISSUE THREAD

**Issue by bsharma2000** [brianbianco/redisio#308]
Does this need to be added to the [sentinel.conf template](https://raw.githubusercontent.com/brianbianco/redisio/master/templates/default/sentinel.conf.erb)?
 
Or is there a different way to specify that via Chef? 

Also noticed that the conf file referenced in http://download.redis.io/redis-stable/sentinel.conf makes a reference to this parameter (*# protected-mode no*) but the the template referenced above does not.

**Comment by threestarsgenius** [comment]
@bsharma2000 i guess that the only way how to specify this param is to update `sentinel.conf.erb`. I've spent some time on this and didn't found any other way.

**Comment by shortdudey123** [comment]
Solved by https://github.com/brianbianco/redisio/pull/275
