### ISSUE TITLE
Systemd template uses `redis['default_settings']['maxclients']`

### ISSUE THREAD

**Issue by altvnk** [brianbianco/redisio#316]
Systemd template uses `redis['default_settings']['maxclients']` in [configure.rb] recipe (https://github.com/brianbianco/redisio/blob/master/recipes/configure.rb#L45)
This causes that this value cannot be overridden with `redisio['servers']['maxclients'` and systemd service always receives default file limit 10000. So redis server refuses settings in `maxclients` key and reduces it to maximum possible:
```
You requested maxclients of 100000 requiring at least 100032 max file descriptors.
Current maximum open files is 10032. maxclients has been reduced to 10000 to compensate for low ulimit
```
Resulting piece of systemd unit file:
```
[Service]
ExecStart=/usr/bin/redis-server /etc/redis/%i.conf --daemonize no
ExecStop=/usr/bin/redis-shutdown
User=redis
Group=redis
LimitNOFILE=10032
```
I suggest changing this to `current['maxclients']` which is respects user settings.

**Comment by shortdudey123** [comment]
@brownc feel free to make a PR and i will take a look at it, thanks!!

**Comment by shortdudey123** [comment]
actually it looks like https://github.com/brianbianco/redisio/pull/302 covers this

**Comment by shortdudey123** [comment]
Solved by https://github.com/brianbianco/redisio/pull/302
