### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by shortdudey123** [brianbianco/redisio#323]
@brianbianco I saw your comment that you are looking for new maintainers
If you are still looking, i can help out
If you are looking to transfer the cookbook as a whole, the Sous Chefs can take it

**Comment by brianbianco** [comment]
Sure i think it would be great if you helped maintain the cookbook.  You'll also need supermarket access so you can cut releases.

**Comment by shortdudey123** [comment]
Sounds good!  You can add me here then or transfer the repo to me... which ever you prefer

**Comment by brianbianco** [comment]
Hop on the redisio gitter if you get a chance so we can have a quick chat.
